### ISSUE TITLE
mpvnet compability

### ISSUE THREAD

**Issue by bitsper2nd** [darsain/uosc#10]
hi I am using mpvnet and your script doesn't seem to be working with it. I already followed the instructions oh the read.md but nothing.

**Comment by darsain** [comment]
The readme instructions are for mpv. I have no experience with mpv.net, don't even know what it'd take to make it compatible, and honestly I don't want to maintain the compatibility layer for it.

It's already a bit annoying to target and test on different OSs. Adding support for mpv forks I'm not interested in seems like a maintenance hell someone would have to pay me for to go through.

So I'm really happy you are interested in usoc, but unfortunately I can't help you with this.

**Comment by bitsper2nd** [comment]
thx for the reply. I will see what I can do in my free time and learn more about mpv scripting. if I get any results, I will do a pull request.

**Comment by darsain** [comment]
Don't waste time with a PR. As I've said, this project targets only mpv. I don't want to maintain support for every mpv fork someone requests in the future. I'd go crazy.

**Comment by plu5** [comment]
Just to note here: I use mpv.net (5.4.8.0) and it does work. Thank you for making uosc and for making it easy to customise. I really like it.

A potential pitfall for users new to mpv: if you’re putting the script in the installation folder, it needs to be in `/portable_config/scripts`, not in `/Scripts`. And as the readme mentions, have `osc=no` and `osc-bar=no` in `/portable_config/mpv.conf` or you’ll just get the default osc.
