### ISSUE TITLE
Unable to bring up widgets after seeking

### ISSUE THREAD

**Issue by HelpSeeker** [darsain/uosc#11]
When following the steps below uosc's widgets won't be shown as long as the cursor stays within the window. Moving the cursor outside the window resets the widget responsiveness.

Steps to reproduce:

* Set `autohide=yes` and `title=yes`
* Seek without using the uosc (e.g. arrow keys) and don't have a widget active
* Move cursor to any widget location without leaving the window borders

**Comment by darsain** [comment]
ty
