### ISSUE TITLE
Add back a way to display chapters on top of elapsed timeline

### ISSUE THREAD

**Issue by po5** [darsain/uosc#118]
Specifically for `timeline_style=bar`.  
I found the old behavior more useful.

**Comment by tomasklaen** [comment]
Uhm, I don't really know what you mean. If you want chapters to be rendered on top of the progress bar, that's what the new `timeline_elements` option is for. It not only controls what elements to render, but in what order, so just reshuffle the default `ranges,chapters,progress,cache,time` to `progress,ranges,chapters,cache,time`.

**Comment by tomasklaen** [comment]
Though I might change it before the next release. Not happy with needing `timeline_elements` option.

**Comment by po5** [comment]
Didn't realize that option was introduced, thanks.

**Comment by manfred3000** [comment]
This is my first comment on this project, so first of all I'd like to express my appreciation for this awesome UI - Thank you!

This is also a +1 comment in the sense that I personally prefer not having rendered "anything" on top of the actual (video) output - or to put it this way:
Is there currently a way to show chapters without overlapping the video screen?

Thanks again and have great day!
