### ISSUE TITLE
How to disable fade in/out effect?

### ISSUE THREAD

**Issue by relaxeaza** [darsain/uosc#13]

**Comment by darsain** [comment]
Set `proximity_in` and `proximity_out` to the same value.

**Comment by darsain** [comment]
Actually, set `proximity_out` to 1 px bigger than `proximity_in`, or it'll break. I'll fix it.

**Comment by darsain** [comment]
Download new version though. I fixed a piece of code that was dividing by 0 if you had both at the same value.
