### ISSUE TITLE
Show title without window controls

### ISSUE THREAD

**Issue by FichteFoll** [darsain/uosc#15]
I run mpv on i3 in floating mode and window decorations disabled (by i3) and I   need mpv's borders. I don't have a need for the window controls, since I use a key binding to close windows and the other two buttons do nothing, but I would like to see the title of the video when hovering the top area. This doesn't seem to be possible at the moment.

TL;DR show title with border but no window controls

**Comment by FichteFoll** [comment]
Thank you for the quick fixes.

However, it seems that showing the top bar still requires `--no-border`, which I don't want to lose. Could you lift that requirement as well?

**Comment by darsain** [comment]
Todo:
- `top_bar=never|no-border|fullscreen|always`

**Comment by barolo** [comment]
> Todo:
> 
>     * `top_bar=never|no-border|fullscreen|always`
> 
> 
> Although I feel like uosc is getting a case of options creep since I'm adding options that will be used by 0.0001% of users.

`border=no` prevents some apps from keeping track of closed state of mpv, [example](https://github.com/jellyfin/jellyfin-mpv-shim/issues/110)
So I prefer disabling border through window manager and would like to have contrels detached from` border=no` requirement

**Comment by FichteFoll** [comment]
Thank you, much appreciated.
