### ISSUE TITLE
Hide UI when cursor is autohidden

### ISSUE THREAD

**Issue by darsain** [darsain/uosc#2]
So I wanted to implement this, but I can't find any event or other hook that would notify me when mpv hides the cursor hovering the video due to inactivity.

If anyone knows about an event like that, please let me know.

I think it would also be possible to get cursor autohide timing setting, and set up a timer with this value on last mouse_move event, but this feels too dirty, and would require canceling/restarting timer on every mouse_move. I really don't like this and will leave it as a last resort option.

**Comment by po5** [comment]
What I do in https://github.com/po5/libass_sub_selector is store the last time the mouse was moved, and compute when to hide the cursor from `mp.get_property_native("cursor-autohide")`.

It's basically reimplementing the entire autohide behavior, but seems that's the only way.
Hope this helps.

**Comment by darsain** [comment]
Yeah that's exactly what I described in the 3rd paragraph above that I don't want to do, but I guess it can't be helped and there is no other way around it. I'll add it in next version.
