### ISSUE TITLE
Installation instructions are too short

### ISSUE THREAD

**Issue by stefanhusmann** [darsain/uosc#25]
In your README you write that the file uosc.lua has to be copied into the scripts folder. I do not have such a folder. "man lua" does not mention it either.

I think this is an end user program, and end users tend not to know anything about lua (like me). So the description should be mor comprehensive.

**Comment by darsain** [comment]
This has nothing to do with lua or uosc. This is your mpv scripts folder. If you want to learn how to install scripts into mpv, read mpv documentation. It describes all the locations where mpv user directory can be on all systems.

In other words, it's not uosc responsibility to tell you all the locations where you could've installed your mpv.

**Comment by regulator-g** [comment]
Agreed..
-I put the uosc in .config/mpv/scripts
-disable OSD in mpv.conf
-start MPV and cant see the new OSD
I even looked at MPVs documentation and there's no clear page on scripts it just says you can use them and to put them in your scripts folder

**Comment by tomasklaen** [comment]
Here's the documentation: https://mpv.io/manual/master/#files
I'll add a link to it to readme I guess.
