### ISSUE TITLE
Current and remaining times don't update at the same time

### ISSUE THREAD

**Issue by po5** [darsain/uosc#26]
Can be very distracting.

**Comment by darsain** [comment]
I definitely don't think this can be **very** distracting. I've never even noticed until you pointed it out.

uosc just observes mpv properties, so it updates these values as soon as mpv updates *its* values. And these values are correct, in sync with what they are representing.

Think about it. If video is 10.5 seconds long, `remaining_time` will update half a second before `current_time`. Video duration would have to be "rounded" to seconds for these values to be in sync.

I'm definitely not going to add any artificial synchronization which would lead to incorrect times being displayed just to satisfy someones OCD :)
