### ISSUE TITLE
Feature request: Chapters

### ISSUE THREAD

**Issue by po5** [darsain/uosc#3]
Maybe in a style similar to torque's progressbar https://github.com/torque/mpv-progressbar

Would also be really nice to update the chapter display on the fly, to work with scripts adding chapters like https://github.com/thebombzen/scripts/blob/master/src/lua/markchapter.lua

**Comment by darsain** [comment]
I've actually had chapters working on my local version for weeks now, but I'm undecided on what kind of styling to use 😳. Here are my current candidates:

![image](https://user-images.githubusercontent.com/538801/78182027-acedb580-7465-11ea-848b-d8fb6e408ed0.png)

**Comment by po5** [comment]
I quite like the dots. Also, sent you a DM on Discord about misc deas to not pollute github issues.
