### ISSUE TITLE
"uosc/delete-file-quit" fails to delete file

### ISSUE THREAD

**Issue by maliayas** [darsain/uosc#32]
In my setup, the command merely quits the file; it doesn't delete it. Anyone having the same issue?

    SHIFT+DEL   script-binding uosc/delete-file-quit

Tested on:

- Windows 7
- mpv 20200510-git-4e94b21

**Comment by darsain** [comment]
No idea. All works fine in Win10. You can try modifying line [3214](https://github.com/darsain/uosc/blob/master/uosc.lua#L3214) (end of the file):

```lua
os.remove(normalize_path(path))
```
to 
```
print(normalize_path(path))
```

And check if it'll produce correct path to the file.

You need to start mpv from command line to see prints. Or remove the `mp.command('quit')` line below it and toggle mpv console with `~`.

**Comment by maliayas** [comment]
Thanks for the quick reply. I did that and found it's about non-ASCII characters in the filename. For now, I suspect that's a problem with my PC's configuration; today I'll make some changes and try again. I'll update/close the issue later today.

Thanks again.

**Comment by po5** [comment]
Newer builds by shinchiro should work fine with unicode filenames.

**Comment by maliayas** [comment]
> Newer builds by shinchiro should work fine with unicode filenames.

Thanks for pointing out. Unfortunately `20200621-git-dc24a43` didn't work for me either.

> For now, I suspect that's a problem with my PC's configuration

It turns out that, it's not about my configuration. There is a bug somewhere. To simply reproduce the bug, rename a video file to `ö.mkv` and run the command; it closes the file but doesn't delete it.

**Comment by darsain** [comment]
I was using lua's `os.remove()` function to delete files, which seems to not be able to handle paths with unicode characters in them...

I've switched to OS specific file deletion commands (`cmd /C del file` and `rm file`). Try the latest master. It should work now.

**Comment by maliayas** [comment]
Yes, it's working great. Thanks very much.
