### ISSUE TITLE
Squares in the menu

### ISSUE THREAD

**Issue by ogsdu** [darsain/uosc#36]
![image](https://user-images.githubusercontent.com/24895792/89666685-cafe7300-d8a8-11ea-949b-9ba21e6088b3.png)

**Comment by darsain** [comment]
Probably some weird character at the end of each line that defines menu items. Check in your `input.conf` and its encoding.

**Comment by po5** [comment]
Can confirm, switching line endings fixes it.
Would be good to just ignore those on uosc's side.

**Comment by ogsdu** [comment]
True. Changing to LF fixed the issue. Thanks!
