### ISSUE TITLE
Doesn't hide timeline in full screen if it matches video resolution

### ISSUE THREAD

**Issue by FichteFoll** [darsain/uosc#39]
If the full-screened mpv window is at the same resulution as the source video, uosc still displays the progress bar despite `timeline_size_min_fullscreen=0` (the default).

**Comment by darsain** [comment]
Try [9689b26/uosc.lua](https://raw.githubusercontent.com/darsain/uosc/9689b2620b87dd7ba51f6c3890922302c5a65e2c/uosc.lua).

**Comment by FichteFoll** [comment]
Thanks, that works.
