### ISSUE TITLE
Command to flash pause indicator

### ISSUE THREAD

**Issue by po5** [darsain/uosc#40]
Similar to flash-timeline, flash-volume, and flash-speed.
I would like to only display the pause indicator when pressing specific keys.

**Comment by darsain** [comment]
If there is anyone else that would have a use for this -> 👍, and maybe add what the use case might be.

But atm this looks to me like a feature request that would require refactoring pause indication and supporting this feature in the future for 1 person in the world :)

**Comment by FichteFoll** [comment]
Would `pause_indicator=static` suffice?
