### ISSUE TITLE
Add a simple window border 

### ISSUE THREAD

**Issue by he2a** [darsain/uosc#41]
An option to add a simple border overlay of customizable thickness and color around the window when `no-border` is detected in mpv.

**Comment by darsain** [comment]
So you want to remove a border to add a border? :)

But to be honest, I'd also like a 1px black border around the window. The reason why I didn't attempted it is that I don't just want to draw a border over video and hide parts of it, so it would have to be drawn outside the video area, and there is to my knowledge no clear way how to do it. It would have to be done by I guess resizing the window, than zooming and panning the video out, and recoloring the window background. This would I suspect produce a lot of bugs and it would either brake a lot of things, or make them very uncomfortable, if not unusable.

Like making it work when user is manually changing panning, zoom, aspect ratio, ... it would be a nightmare to implement and iron out all the edge cases (if it's even possible) and I'm really not willing to waste so much time on such an un-impactful feature.

If there are some mpv options that make it possible let me know.

In any case, I have a lot of other work to do now and in far foreseeable future, so can't make any promises.

**Comment by he2a** [comment]
Well honestly the uosc window controls looks way better than the windows 10 default window controls, but the only problem preventing me from going no-border is that the video often blends with the surrounding without any border.

Theres a hacky way to implement it without sacrificing the video portion like its done in [https://github.com/occivink/mpv-scripts/blob/master/scripts/blur-edges.lua](url) but it cuts performance a lot for weak systems since its basically editing each video frame and as expected very unstable.

Honestly I don't see any problem sacrificing 1px of video content, the uosc timeline already has an option to do it. A low opacity of 15% or 20% should be a reasonable compromise but it would be preferable imo to have the same color and opacity as the timeline border for consistency.

**Comment by darsain** [comment]
All right, this was a bit more work than I hoped for but you can try it on [dev branch](https://github.com/darsain/uosc/tree/dev).

**Comment by he2a** [comment]
It's perfect thanks a lot! 👍
