### ISSUE TITLE
feature request: option to always show uosc when playing audio

### ISSUE THREAD

**Issue by junguler** [darsain/uosc#42]
hi, i always use mpv on window mode when listening to audio, with the default osc there was an option to toggle visibility and i like to have the same functionality with uosc if possible, thanks.

**Comment by darsain** [comment]
Sure, sounds reasonable. I'm thinking just an internal audio mode that makes everything 100% opacity when stream has no video. Or is there a reason for adding an option?

**Comment by junguler** [comment]
that works for me too, i only mentioned an option or toggle because you might have not wanted to change how your osc works, now that you agree with my suggestion it's a mute point. 
thanks for your amazing project, feel free to close this issue whenever you want.

**Comment by darsain** [comment]
Added persistency options. You can get the development version with it here:

https://raw.githubusercontent.com/darsain/uosc/dev/uosc.lua

It enables elements to always be visible in configured states.
For example, setting `timeline_persistency=paused,audio` will make timeline always visible when playback is paused, or when audio file is open.

Available states: paused, audio

To have all elements visible when playing audio, add this to your config:

```
timeline_persistency=audio
volume_persistency=audio
speed_persistency=audio
top_bar_persistency=audio
```

**Comment by junguler** [comment]
amazing work, thank you.
