### ISSUE TITLE
Is there a way to modify the response area?

### ISSUE THREAD

**Issue by vvyoko** [darsain/uosc#43]
Like the script [progressbar.lua](https://github.com/torque/mpv-progressbar)

The first setting ` hover-zone-height=` in [torque-progressbar.conf](https://github.com/torque/mpv-progressbar)
can modify the response area.

It allows me to adjust a large area above the progress bar.

Then I can set the progress height to 5 or smaller and it doesn't affect my operation.

Just like in the picture, click on the mouse location to adjust the progress.
Although not what you see is what you get.
![1](https://user-images.githubusercontent.com/2145741/100306939-83c6fa00-2fdf-11eb-95e8-a801aed5ada4.jpg)

**Comment by darsain** [comment]
If you are asking to be able to seek by clicking on empty area above seekbar than no, sorry, thats a wontfix.

It's a bad UI design for once, but also the area above seekbar is a real estate for speed control and other control elements I might implement in the future.

**Comment by vvyoko** [comment]
ok
Although I don't think it's a bad design.
Maybe you think you need to click on something.

But this is the same as the left click to pause and right click menu.

And that's not without any hints, there is a time under the mouse to indicate the exact location you will move to

I think it fits the small, unintrusive of what it says.
