### ISSUE TITLE
some small suggestions

### ISSUE THREAD

**Issue by Harze2k** [darsain/uosc#47]
Hi!

Again awesome work man! Using it everyday :)

1) When you are in a sub menu, and you want to change to another submenu that's in another option. Please make it so that you can go directly there just by pressing the link in the main menu. Right now when you do that, you get back to the main menu as expected but you have to click again on the option that you wanted to visit. Just smoother this way , can make it an option perhaps?

2) When you click an item in the menu, if that sub menu has like 2 options, wouldn't it be easier if those pops out to the right at the height of where the mouse cursor already is?  

3) Would it be possible to show the value you already have licked on and is active? Say i have options for something and i have just enabled that. I get back again to the menu and would be nice to "see" that its active. Might be a stretch but would be nice.

Cheers!

**Comment by darsain** [comment]
1. And how will you go back to the parent menu? I don't want an inconsistency where clicking on some menu items will go back, and some will activate. That would drive me insane.
2. Risking drawing outside the window. Active menu has to be in the center.
3. uosc has no idea about what any menu option does, so it can't apply any context to them. In situation where we do have that information (custom menus like selecting subtitles/audio/files) it already shows what is currently active.

These are all good UX suggestions, but mpv UI rendering API is a very constraint environment, and tough compromises have to be made, so implementing any of them is either impossible (3.) or would lead to bigger issues (1., 2,).
