### ISSUE TITLE
Menu with extra symbol at the end of the text

### ISSUE THREAD

**Issue by jack2game** [darsain/uosc#50]
![Menu](https://user-images.githubusercontent.com/16070158/117041128-3775a800-ad3d-11eb-9fa3-9a6fe558b218.png)

More of a compatibility issue than an actual error:

After some digging, apparently my input.conf has Windows format EOL (CRLF) instead of the Linux EOL (LF).

After converting my file to Linux EOL, all menu titles can display correctly.

**Comment by darsain** [comment]
Hm... that's weird. I've tried converting my input.conf to CRLF and it didn't produce this issue.

Seems to me like your build has a lua runtime where `io.lines()` ignores `\r` when splitting files into lines.

**Comment by jack2game** [comment]
Probably that's because I'm using a Windows build in the first place, specifically this one:

https://sourceforge.net/projects/mpv-player-windows/files/

**Comment by RozeFound** [comment]
Yep. Same setup, same error, same solution.

**Comment by lotspecter** [comment]
Change font menu. I try this fonts [https://fonts.google.com/specimen/Titillium+Web#standard-styles](url) that work.

**Comment by tomasklaen** [comment]
I think this was fixed in one of the recent PRs. Let me know if not and I'll reopen.
