### ISSUE TITLE
Volume disappears when the mouse below down half of the window on the right 

### ISSUE THREAD

**Issue by trappedinspacetime** [darsain/uosc#51]
Very nice script, congrats! I like adjusting volume via dragging  the mouse.
I noticed that when the mouse goes down bottom right part of the window, volume icon goes hidden, so, starting the dragging is difficult.

**Comment by darsain** [comment]
Volume control hides when you hover timeline to not collide with timestamp text. Is this what is causing you a problem? Did you make your timeline too big?

**Comment by trappedinspacetime** [comment]
@darsain Thank you for your help. It's my bad, it stemmed from buit-in osc since I added `player-operation-mode=pseudo-gui` to mpv.conf.
If I remove it, it works well. But I  couldn't figure out how to restrict osc  to only its premise, its mouse-over triggering area  occupies whole bottom of the window.

**Comment by trappedinspacetime** [comment]
osc.conf :


        layout=bottombar
        seekbarstyle=diamond
        seekbarhandlesize=1
        deadzonesize=0.98
fixed my issue.

**Comment by darsain** [comment]
Built in osc should be disabled when this one is used. You are asking for issues by running 2 at the same time.
