### ISSUE TITLE
How to add windows minimize and close animation?

### ISSUE THREAD

**Issue by CasperXu** [darsain/uosc#57]
Is it possible to add windows minimize and close animation to this osc?  
I love this osc but I am a little bit not used to the top_bar.
When I click on closing or minimizing the window,  it has no animation, while the original mpv's osc has it.
So I wonder if the animation can be added or not.

**Comment by darsain** [comment]
uosc just uses mpv's built in minimize and close commands, so that's the place where to ask about it.

And you can of course always re-enable window border.
