### ISSUE TITLE
Ambiguous tracks in audio track selection

### ISSUE THREAD

**Issue by nokicheru** [darsain/uosc#58]
Different audio tracks can become indistinguishable in files with multiple audio tracks of the same language. Often, those tracks contain different formats, channel layouts or sample rates which could be displayed in addition to the language of the track.

An example of this being implemented in the track selection in mpv.net:
![example](https://user-images.githubusercontent.com/91436030/134824438-90d8db90-f720-47a9-9f70-d9b9c56040bb.png)

This would make track selection much easier (in certain cases).

**Comment by hooke007** [comment]
mpvnet use mediainfo to read msg of tracks, not mpv.

**Comment by tomasklaen** [comment]
When I'll have some time I'll look at it. If that data is available, it shouldn't be an issue adding it next to the track name.
