### ISSUE TITLE
Open url button

### ISSUE THREAD

**Issue by dtomvan** [darsain/uosc#62]
Is there a way (in uosc) to open a URL from the menu?

**Comment by tomasklaen** [comment]
to open a url, just drag it into mpv, or  I think  there is a copy & paste script in mpv wiki so you can ctrl+v as well. usoc doesn't handle opening files apart of navigation in current dolder/playlist.

**Comment by FichteFoll** [comment]
Yeah, there are three scripts listed on the [wiki page](https://github.com/mpv-player/mpv/wiki/User-Scripts).
