### ISSUE TITLE
Script simply does not get loaded by MPV

### ISSUE THREAD

**Issue by uptightgnome** [darsain/uosc#64]
MPV does not recognize the script at all after updating to new uosc version. Other scripts work fine and the previous version did as well. I've tried moving the script to the mpv directory as well as a portable config.

[Log file](https://pastebin.com/ZYWQDdTh)

**Comment by tomasklaen** [comment]
I don't see anything uosc related in that log file. Also just tested the newest script on both windows and linux machines and works fine.

So no idea what your issue might be. Sorry.

**Comment by uptightgnome** [comment]
Turns out I accidentally downloaded the webpage instead of the actual lua file. How embarrassing.
