### ISSUE TITLE
uosc/stream-quality doesn't work as an option in the menu, but it does with a key bind.

### ISSUE THREAD

**Issue by pawa2401** [darsain/uosc#70]
When I assign a key bind to it, it works.
(h			script-binding uosc/stream-quality #! Video > Stream Quality)
When it is only as a GUI option, the selection menu doesn't appear.
(#			script-binding uosc/stream-quality #! Video > Stream Quality)
Log:
[  24.051][e][input] Command 'uosc/stream-quality' not found.
[  24.051][e][input] Command was defined at uosc.

**Comment by tomasklaen** [comment]
Can't reproduce, works fine either way for me. Are you perhaps entering the brackets around your examples as well?

And are you using the latest version?

**Comment by pawa2401** [comment]
No. I am not using the brackets in the input.conf
And it seems like I have the newest version, because I downloaded it on the 26th (5d ago).

**Comment by pawa2401** [comment]
Redownloading mpv solved the issue. I don't know what happened. Sorry for the trouble.
