### ISSUE TITLE
Option to open a certain folder from menu

### ISSUE THREAD

**Issue by Zabooby** [darsain/uosc#72]
I store all my movies/shows in the videos folder on windows. When I open mpv with nothing loaded I use the open-file option to open the user directory then the videos folder. 

I was wondering if there was a way to open the videos folder directly, I get that it is only a one click difference but it would streamline my experience and this feature might be useful for other users.

**Comment by tomasklaen** [comment]
Download the newest `uosc.lua` and add to your `mpv/script-opts/uosc.conf`:

```
default_directory=~/Videos
```

Or whatever your paths is.

**Comment by Zabooby** [comment]
Wow that was fast, it works perfectly! 
Thanks for the help, been using your ui since I found out about mpv!
