### ISSUE TITLE
link `default_directory` to the current playing file's dir?

### ISSUE THREAD

**Issue by hooke007** [darsain/uosc#76]
As described in the title, is it possible to implement the func?

**Comment by tomasklaen** [comment]
That's already the current behavior. If you are playing local file, open file menu will always open at the file's current directory.

The `default_directory` option is only to tell uosc where to open the menu if the directory of currently playing video can't be determined, such as when playing streams.

**Comment by hooke007** [comment]
Oh sry, I forgot I was watching the imgs on the Internet.
