### ISSUE TITLE
[bug] about `menu_button=center`

### ISSUE THREAD

**Issue by hooke007** [darsain/uosc#77]
Sometimes the menu would quickly disappear when I click the menu button to call the menu

https://user-images.githubusercontent.com/41094733/170742449-b88ac641-365a-44b3-9914-18812bb18346.mp4

Tested by your repo's sample file. only `--no-osc` used in the mpv.conf

**Comment by tomasklaen** [comment]
Yeah, can replicate. I'll look at it when I have some time.
