### ISSUE TITLE
change the speed via the widget may make uosc crash

### ISSUE THREAD

**Issue by hooke007** [darsain/uosc#78]
Hello, here is the another weird bug.
1. add the speed by the default shortcut
2. press the speed button and quickly move 
3. Sometimes it would crash the uosc (even mpv)

![Snipaste_2022-05-27_20-25-32](https://user-images.githubusercontent.com/41094733/170777702-b3a01035-d293-4458-990e-89750d7a8173.jpg)

**Comment by hooke007** [comment]
https://user-images.githubusercontent.com/41094733/170778412-017e51c8-6485-4910-921a-4a52d790d5a9.mp4

**Comment by christoph-heinrich** [comment]
An easy way to reproduce this, is to drag the speed and then let go while the mouse is over the timeline.
