### ISSUE TITLE
Last character in right click menu entries is a box character

### ISSUE THREAD

**Issue by sbstratos79** [darsain/uosc#82]
Right click menu entries have a box as a trailing character.
![image](https://user-images.githubusercontent.com/4395586/176170890-542a0c71-ab32-4e30-b84d-ec98c0cf55fb.png)

I haven't added this character in the config.
![image](https://user-images.githubusercontent.com/4395586/176170327-997b5a1f-f2e9-464e-8aff-15c46b420c0c.png)

mpv 0.34.0-285-g9ffaa6b81b, Windows 11

**Comment by tomasklaen** [comment]
#36 Switch your line endings to LF.

Keep the issue open though to remind to strip CR during config parsing.

**Comment by sbstratos79** [comment]
Thanks! Switching line endings to LF fixed the issue. I will keep this issue open.
