### ISSUE TITLE
next/prev-file does not work when playing files from network share

### ISSUE THREAD

**Issue by Leondre** [darsain/uosc#83]
The next-file or prev-file commands do not work and output an error when playing a file from a smb share. If I move the files to my local machine the commands work as expected.

![Screenshot 2022-06-28 154035](https://user-images.githubusercontent.com/5105360/176284476-fd0772dd-fdeb-4999-aff9-7e636b518167.jpg)

Windows 11

**Comment by tomasklaen** [comment]
Finally had some time to look at this. We are using [`mp.utils.readdir`](https://mpv.io/manual/master/#lua-scripting-utils-readdir(path-[,-filter])) to list files inside a directory, so this seems to be an upstream issue in utils library provided by mpv.

I didn't find any issues about it, so I guess try using the latest mpv if it isn't already fixed. If not, report an issue at [mpv repo](https://github.com/mpv-player/mpv).

I'll close this for now, but if you happen to run into a solution I could implement on my end, let me know and I'll reopen.
