### ISSUE TITLE
Show chapter name together with timestamp when hovering over seek bar

### ISSUE THREAD

**Issue by FichteFoll** [darsain/uosc#85]
Especially when watching videos from youtube, chapters can be quite useful for determining where in the video you're currently hovering at as an alternative to the chapter list you can already open explicitly. A very similar feature is provided by youtube itself, e.g. on https://www.youtube.com/watch?v=XMn0OM0eWDU

![2022-07-05_17-28-58](https://user-images.githubusercontent.com/931051/177363715-a07165ad-5983-4c19-bde2-0444b35f5d0c.png)

PS: searching for "chapter" in this repo's issue almost exclusively yields issues from myself, huh.

**Comment by tomasklaen** [comment]
Yup, would be nice. Another thing on a to-do list :)
