### ISSUE TITLE
Is there any way to style window controls?

### ISSUE THREAD

**Issue by smowtenshi** [darsain/uosc#86]
Currently only close button has red background, but I'd like all of these to match my Plasma buttons, which look like this ![plasma](https://files.catbox.moe/leklsj.png)

Is it possible to change background of minimize and maximise buttons too?

**Comment by tomasklaen** [comment]
It's not. I suggest just not disabling and using your desktop window bar if you want to match it so closely.

Adding styling options for every rectangle this script renders is unreasonable imo. Sorry about that 😞.
