### ISSUE TITLE
Configurable rendering frequency

### ISSUE THREAD

**Issue by christoph-heinrich** [darsain/uosc#90]
I've just tried setting `config.render_delay` to 1/60 and the difference in smoothness is quite noticeable.

Simply moving `render_delay` to `options` isn't a good solution, as this would only allow setting numbers and not expressions (like `1/60`). Maybe introducing an option for rendering frequency that then gets converted into `render_delay` would be a better solution (`config.render_delay = 1/options.render_frequency`).

Not sure what the best approach would be, since you don't like introducing new options.

**Comment by tomasklaen** [comment]
The main problem with rendering frequency is that it's respected only when the player is paused. That's when we can render at display's refresh rate. But when the video is playing, the osd only updates once per video frame, so the UI is going to be as smooth as video's framerate allows.

But I don't mind making it 1/60 by default to make it smoother at least when paused.
I don't want to add an option here, cause people might configure it just to realize it's ignored half the time, and that would piss them off. It would piss me off, and my first question would be "well what's the point of making it configurable if mpv just ignores it then" :)

**Comment by christoph-heinrich** [comment]
I think with `video-sync=display-resample` and `interpolation` it always renders at the display's refresh rate, but you are right, there would certainly be some people that would get confused.

**Comment by christoph-heinrich** [comment]
We could use [`estimated-display-fps`](https://mpv.io/manual/stable/#command-interface-estimated-display-fps) if available, otherwise [`display-fps`](https://mpv.io/manual/stable/#command-interface-display-fps) and `config.render_delay` as a fallback.
I'll create a PR if that approach is fine with you.

**Comment by tomasklaen** [comment]
> I think with video-sync=display-resample and interpolation it always renders at the display's refresh rate

I thought so too, but in practice I don't see much difference.

> I'll create a PR if that approach is fine with you.

Sure, no objections.
